// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: ghost.proto

package protocol

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FocusState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WindowTitle    string                 `protobuf:"bytes,1,opt,name=window_title,json=windowTitle,proto3" json:"window_title,omitempty"`
	ProcessName    string                 `protobuf:"bytes,2,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	UiTreeSnapshot string                 `protobuf:"bytes,3,opt,name=ui_tree_snapshot,json=uiTreeSnapshot,proto3" json:"ui_tree_snapshot,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FocusState) Reset() {
	*x = FocusState{}
	mi := &file_ghost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusState) ProtoMessage() {}

func (x *FocusState) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusState.ProtoReflect.Descriptor instead.
func (*FocusState) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{0}
}

func (x *FocusState) GetWindowTitle() string {
	if x != nil {
		return x.WindowTitle
	}
	return ""
}

func (x *FocusState) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *FocusState) GetUiTreeSnapshot() string {
	if x != nil {
		return x.UiTreeSnapshot
	}
	return ""
}

type PermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        string                 `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	Actions       []*Action              `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	mi := &file_ghost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *PermissionRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PermissionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type PermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	TrustScore    int32                  `protobuf:"varint,3,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResponse) Reset() {
	*x = PermissionResponse{}
	mi := &file_ghost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResponse) ProtoMessage() {}

func (x *PermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResponse.ProtoReflect.Descriptor instead.
func (*PermissionResponse) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *PermissionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PermissionResponse) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "CLICK", "TYPE", "EXEC", "SPEAK"
	Payload       map[string]string      `protobuf:"bytes,2,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_ghost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Action) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ActionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action        *Action                `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionCommand) Reset() {
	*x = ActionCommand{}
	mi := &file_ghost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCommand) ProtoMessage() {}

func (x *ActionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCommand.ProtoReflect.Descriptor instead.
func (*ActionCommand) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{4}
}

func (x *ActionCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ActionCommand) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type PendingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PendingItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingList) Reset() {
	*x = PendingList{}
	mi := &file_ghost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingList) ProtoMessage() {}

func (x *PendingList) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingList.ProtoReflect.Descriptor instead.
func (*PendingList) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{5}
}

func (x *PendingList) GetItems() []*PendingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PendingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	RiskScore     int32                  `protobuf:"varint,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingItem) Reset() {
	*x = PendingItem{}
	mi := &file_ghost_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingItem) ProtoMessage() {}

func (x *PendingItem) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingItem.ProtoReflect.Descriptor instead.
func (*PendingItem) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{6}
}

func (x *PendingItem) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *PendingItem) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *PendingItem) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

type ApprovalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_ghost_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{7}
}

func (x *ApprovalDecision) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ApprovalDecision) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type ModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"` // "*" or "browser"
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`     // "AUTO", "MANUAL"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeRequest) Reset() {
	*x = ModeRequest{}
	mi := &file_ghost_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeRequest) ProtoMessage() {}

func (x *ModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeRequest.ProtoReflect.Descriptor instead.
func (*ModeRequest) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{8}
}

func (x *ModeRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ModeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SystemState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // "ACTIVE", "SHADOW", "PAUSED"
	ActiveFocus   string                 `protobuf:"bytes,2,opt,name=active_focus,json=activeFocus,proto3" json:"active_focus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemState) Reset() {
	*x = SystemState{}
	mi := &file_ghost_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemState) ProtoMessage() {}

func (x *SystemState) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemState.ProtoReflect.Descriptor instead.
func (*SystemState) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{9}
}

func (x *SystemState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SystemState) GetActiveFocus() string {
	if x != nil {
		return x.ActiveFocus
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ghost_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ghost_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ghost_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ghost_proto protoreflect.FileDescriptor

const file_ghost_proto_rawDesc = "" +
	"\n" +
	"\vghost.proto\x12\x05ghost\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"|\n" +
	"\n" +
	"FocusState\x12!\n" +
	"\fwindow_title\x18\x01 \x01(\tR\vwindowTitle\x12!\n" +
	"\fprocess_name\x18\x02 \x01(\tR\vprocessName\x12(\n" +
	"\x10ui_tree_snapshot\x18\x03 \x01(\tR\x0euiTreeSnapshot\"o\n" +
	"\x11PermissionRequest\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\x12'\n" +
	"\aactions\x18\x02 \x03(\v2\r.ghost.ActionR\aactions\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"i\n" +
	"\x12PermissionResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vtrust_score\x18\x03 \x01(\x05R\n" +
	"trustScore\"\x8e\x01\n" +
	"\x06Action\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\apayload\x18\x02 \x03(\v2\x1a.ghost.Action.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\rActionCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12%\n" +
	"\x06action\x18\x02 \x01(\v2\r.ghost.ActionR\x06action\"7\n" +
	"\vPendingList\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.ghost.PendingItemR\x05items\"a\n" +
	"\vPendingItem\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x05R\triskScore\"K\n" +
	"\x10ApprovalDecision\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\"9\n" +
	"\vModeRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"F\n" +
	"\vSystemState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12!\n" +
	"\factive_focus\x18\x02 \x01(\tR\vactiveFocus\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa9\x04\n" +
	"\rNervousSystem\x12:\n" +
	"\vReportFocus\x12\x11.ghost.FocusState\x1a\x16.google.protobuf.Empty(\x01\x12H\n" +
	"\x11RequestPermission\x12\x18.ghost.PermissionRequest\x1a\x19.ghost.PermissionResponse\x12?\n" +
	"\rStreamActions\x12\x16.google.protobuf.Empty\x1a\x14.ghost.ActionCommand0\x01\x12X\n" +
	"\x13GetPendingApprovals\x12\x16.google.protobuf.Empty\x1a\x12.ghost.PendingList\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/approvals\x12U\n" +
	"\rApproveAction\x12\x17.ghost.ApprovalDecision\x1a\n" +
	".ghost.Ack\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/v1/approve/{action_id}\x12H\n" +
	"\rSetSystemMode\x12\x12.ghost.ModeRequest\x1a\n" +
	".ghost.Ack\"\x17\x82\xd3\xe4\x93\x02\x11\"\x0f/v1/system/mode\x12V\n" +
	"\x0eGetSystemState\x12\x16.google.protobuf.Empty\x1a\x12.ghost.SystemState\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/system/stateB Z\x1eghost/kernel/internal/protocolb\x06proto3"

var (
	file_ghost_proto_rawDescOnce sync.Once
	file_ghost_proto_rawDescData []byte
)

func file_ghost_proto_rawDescGZIP() []byte {
	file_ghost_proto_rawDescOnce.Do(func() {
		file_ghost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ghost_proto_rawDesc), len(file_ghost_proto_rawDesc)))
	})
	return file_ghost_proto_rawDescData
}

var file_ghost_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ghost_proto_goTypes = []any{
	(*FocusState)(nil),         // 0: ghost.FocusState
	(*PermissionRequest)(nil),  // 1: ghost.PermissionRequest
	(*PermissionResponse)(nil), // 2: ghost.PermissionResponse
	(*Action)(nil),             // 3: ghost.Action
	(*ActionCommand)(nil),      // 4: ghost.ActionCommand
	(*PendingList)(nil),        // 5: ghost.PendingList
	(*PendingItem)(nil),        // 6: ghost.PendingItem
	(*ApprovalDecision)(nil),   // 7: ghost.ApprovalDecision
	(*ModeRequest)(nil),        // 8: ghost.ModeRequest
	(*SystemState)(nil),        // 9: ghost.SystemState
	(*Ack)(nil),                // 10: ghost.Ack
	nil,                        // 11: ghost.Action.PayloadEntry
	(*emptypb.Empty)(nil),      // 12: google.protobuf.Empty
}
var file_ghost_proto_depIdxs = []int32{
	3,  // 0: ghost.PermissionRequest.actions:type_name -> ghost.Action
	11, // 1: ghost.Action.payload:type_name -> ghost.Action.PayloadEntry
	3,  // 2: ghost.ActionCommand.action:type_name -> ghost.Action
	6,  // 3: ghost.PendingList.items:type_name -> ghost.PendingItem
	0,  // 4: ghost.NervousSystem.ReportFocus:input_type -> ghost.FocusState
	1,  // 5: ghost.NervousSystem.RequestPermission:input_type -> ghost.PermissionRequest
	12, // 6: ghost.NervousSystem.StreamActions:input_type -> google.protobuf.Empty
	12, // 7: ghost.NervousSystem.GetPendingApprovals:input_type -> google.protobuf.Empty
	7,  // 8: ghost.NervousSystem.ApproveAction:input_type -> ghost.ApprovalDecision
	8,  // 9: ghost.NervousSystem.SetSystemMode:input_type -> ghost.ModeRequest
	12, // 10: ghost.NervousSystem.GetSystemState:input_type -> google.protobuf.Empty
	12, // 11: ghost.NervousSystem.ReportFocus:output_type -> google.protobuf.Empty
	2,  // 12: ghost.NervousSystem.RequestPermission:output_type -> ghost.PermissionResponse
	4,  // 13: ghost.NervousSystem.StreamActions:output_type -> ghost.ActionCommand
	5,  // 14: ghost.NervousSystem.GetPendingApprovals:output_type -> ghost.PendingList
	10, // 15: ghost.NervousSystem.ApproveAction:output_type -> ghost.Ack
	10, // 16: ghost.NervousSystem.SetSystemMode:output_type -> ghost.Ack
	9,  // 17: ghost.NervousSystem.GetSystemState:output_type -> ghost.SystemState
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ghost_proto_init() }
func file_ghost_proto_init() {
	if File_ghost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ghost_proto_rawDesc), len(file_ghost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ghost_proto_goTypes,
		DependencyIndexes: file_ghost_proto_depIdxs,
		MessageInfos:      file_ghost_proto_msgTypes,
	}.Build()
	File_ghost_proto = out.File
	file_ghost_proto_goTypes = nil
	file_ghost_proto_depIdxs = nil
}
