// Author: Enkae (enkae.dev@pm.me)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: ghost.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NervousSystem_ReportFocus_FullMethodName         = "/ghost.NervousSystem/ReportFocus"
	NervousSystem_RequestPermission_FullMethodName   = "/ghost.NervousSystem/RequestPermission"
	NervousSystem_StreamActions_FullMethodName       = "/ghost.NervousSystem/StreamActions"
	NervousSystem_GetPendingApprovals_FullMethodName = "/ghost.NervousSystem/GetPendingApprovals"
	NervousSystem_ApproveAction_FullMethodName       = "/ghost.NervousSystem/ApproveAction"
	NervousSystem_SetSystemMode_FullMethodName       = "/ghost.NervousSystem/SetSystemMode"
	NervousSystem_GetSystemState_FullMethodName      = "/ghost.NervousSystem/GetSystemState"
)

// NervousSystemClient is the client API for NervousSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// THE NERVOUS SYSTEM
// The Central Nervous System (Kernel) orchestrates all organs.
// Exposes both gRPC (High Speed) and REST HTTP (Human Dashboard).
type NervousSystemClient interface {
	// --- SENSORY INPUT (Body -> Kernel) ---
	// Sentinel streams visual changes to Kernel.
	ReportFocus(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FocusState, emptypb.Empty], error)
	// --- COGNITION (Brain -> Kernel) ---
	// Brain requests permission to act.
	RequestPermission(ctx context.Context, in *PermissionRequest, opts ...grpc.CallOption) (*PermissionResponse, error)
	// --- MOTOR CONTROL (Kernel -> Body) ---
	// Sentinel subscribes to a stream of approved actions.
	StreamActions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionCommand], error)
	// UI asks: "Is there anything waiting for approval?"
	GetPendingApprovals(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PendingList, error)
	// User says: "Yes, do it."
	ApproveAction(ctx context.Context, in *ApprovalDecision, opts ...grpc.CallOption) (*Ack, error)
	// User says: "Switch Mode."
	SetSystemMode(ctx context.Context, in *ModeRequest, opts ...grpc.CallOption) (*Ack, error)
	// Dashboard polling for status
	GetSystemState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemState, error)
}

type nervousSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewNervousSystemClient(cc grpc.ClientConnInterface) NervousSystemClient {
	return &nervousSystemClient{cc}
}

func (c *nervousSystemClient) ReportFocus(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FocusState, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NervousSystem_ServiceDesc.Streams[0], NervousSystem_ReportFocus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FocusState, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NervousSystem_ReportFocusClient = grpc.ClientStreamingClient[FocusState, emptypb.Empty]

func (c *nervousSystemClient) RequestPermission(ctx context.Context, in *PermissionRequest, opts ...grpc.CallOption) (*PermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PermissionResponse)
	err := c.cc.Invoke(ctx, NervousSystem_RequestPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervousSystemClient) StreamActions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActionCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NervousSystem_ServiceDesc.Streams[1], NervousSystem_StreamActions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ActionCommand]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NervousSystem_StreamActionsClient = grpc.ServerStreamingClient[ActionCommand]

func (c *nervousSystemClient) GetPendingApprovals(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PendingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingList)
	err := c.cc.Invoke(ctx, NervousSystem_GetPendingApprovals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervousSystemClient) ApproveAction(ctx context.Context, in *ApprovalDecision, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NervousSystem_ApproveAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervousSystemClient) SetSystemMode(ctx context.Context, in *ModeRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, NervousSystem_SetSystemMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervousSystemClient) GetSystemState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SystemState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemState)
	err := c.cc.Invoke(ctx, NervousSystem_GetSystemState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NervousSystemServer is the server API for NervousSystem service.
// All implementations must embed UnimplementedNervousSystemServer
// for forward compatibility.
//
// THE NERVOUS SYSTEM
// The Central Nervous System (Kernel) orchestrates all organs.
// Exposes both gRPC (High Speed) and REST HTTP (Human Dashboard).
type NervousSystemServer interface {
	// --- SENSORY INPUT (Body -> Kernel) ---
	// Sentinel streams visual changes to Kernel.
	ReportFocus(grpc.ClientStreamingServer[FocusState, emptypb.Empty]) error
	// --- COGNITION (Brain -> Kernel) ---
	// Brain requests permission to act.
	RequestPermission(context.Context, *PermissionRequest) (*PermissionResponse, error)
	// --- MOTOR CONTROL (Kernel -> Body) ---
	// Sentinel subscribes to a stream of approved actions.
	StreamActions(*emptypb.Empty, grpc.ServerStreamingServer[ActionCommand]) error
	// UI asks: "Is there anything waiting for approval?"
	GetPendingApprovals(context.Context, *emptypb.Empty) (*PendingList, error)
	// User says: "Yes, do it."
	ApproveAction(context.Context, *ApprovalDecision) (*Ack, error)
	// User says: "Switch Mode."
	SetSystemMode(context.Context, *ModeRequest) (*Ack, error)
	// Dashboard polling for status
	GetSystemState(context.Context, *emptypb.Empty) (*SystemState, error)
	mustEmbedUnimplementedNervousSystemServer()
}

// UnimplementedNervousSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNervousSystemServer struct{}

func (UnimplementedNervousSystemServer) ReportFocus(grpc.ClientStreamingServer[FocusState, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method ReportFocus not implemented")
}
func (UnimplementedNervousSystemServer) RequestPermission(context.Context, *PermissionRequest) (*PermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPermission not implemented")
}
func (UnimplementedNervousSystemServer) StreamActions(*emptypb.Empty, grpc.ServerStreamingServer[ActionCommand]) error {
	return status.Error(codes.Unimplemented, "method StreamActions not implemented")
}
func (UnimplementedNervousSystemServer) GetPendingApprovals(context.Context, *emptypb.Empty) (*PendingList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingApprovals not implemented")
}
func (UnimplementedNervousSystemServer) ApproveAction(context.Context, *ApprovalDecision) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveAction not implemented")
}
func (UnimplementedNervousSystemServer) SetSystemMode(context.Context, *ModeRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSystemMode not implemented")
}
func (UnimplementedNervousSystemServer) GetSystemState(context.Context, *emptypb.Empty) (*SystemState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemState not implemented")
}
func (UnimplementedNervousSystemServer) mustEmbedUnimplementedNervousSystemServer() {}
func (UnimplementedNervousSystemServer) testEmbeddedByValue()                       {}

// UnsafeNervousSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NervousSystemServer will
// result in compilation errors.
type UnsafeNervousSystemServer interface {
	mustEmbedUnimplementedNervousSystemServer()
}

func RegisterNervousSystemServer(s grpc.ServiceRegistrar, srv NervousSystemServer) {
	// If the following call panics, it indicates UnimplementedNervousSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NervousSystem_ServiceDesc, srv)
}

func _NervousSystem_ReportFocus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NervousSystemServer).ReportFocus(&grpc.GenericServerStream[FocusState, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NervousSystem_ReportFocusServer = grpc.ClientStreamingServer[FocusState, emptypb.Empty]

func _NervousSystem_RequestPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervousSystemServer).RequestPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NervousSystem_RequestPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervousSystemServer).RequestPermission(ctx, req.(*PermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervousSystem_StreamActions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NervousSystemServer).StreamActions(m, &grpc.GenericServerStream[emptypb.Empty, ActionCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NervousSystem_StreamActionsServer = grpc.ServerStreamingServer[ActionCommand]

func _NervousSystem_GetPendingApprovals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervousSystemServer).GetPendingApprovals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NervousSystem_GetPendingApprovals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervousSystemServer).GetPendingApprovals(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervousSystem_ApproveAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovalDecision)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervousSystemServer).ApproveAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NervousSystem_ApproveAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervousSystemServer).ApproveAction(ctx, req.(*ApprovalDecision))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervousSystem_SetSystemMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervousSystemServer).SetSystemMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NervousSystem_SetSystemMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervousSystemServer).SetSystemMode(ctx, req.(*ModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervousSystem_GetSystemState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervousSystemServer).GetSystemState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NervousSystem_GetSystemState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervousSystemServer).GetSystemState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NervousSystem_ServiceDesc is the grpc.ServiceDesc for NervousSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NervousSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ghost.NervousSystem",
	HandlerType: (*NervousSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPermission",
			Handler:    _NervousSystem_RequestPermission_Handler,
		},
		{
			MethodName: "GetPendingApprovals",
			Handler:    _NervousSystem_GetPendingApprovals_Handler,
		},
		{
			MethodName: "ApproveAction",
			Handler:    _NervousSystem_ApproveAction_Handler,
		},
		{
			MethodName: "SetSystemMode",
			Handler:    _NervousSystem_SetSystemMode_Handler,
		},
		{
			MethodName: "GetSystemState",
			Handler:    _NervousSystem_GetSystemState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportFocus",
			Handler:       _NervousSystem_ReportFocus_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamActions",
			Handler:       _NervousSystem_StreamActions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ghost.proto",
}
