# Author: Enkae (enkae.dev@pm.me)
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ghost_pb2 as ghost__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ghost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NervousSystemStub(object):
    """THE NERVOUS SYSTEM
    The Central Nervous System (Kernel) orchestrates all organs.
    Exposes both gRPC (High Speed) and REST HTTP (Human Dashboard).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportFocus = channel.stream_unary(
                '/ghost.NervousSystem/ReportFocus',
                request_serializer=ghost__pb2.FocusState.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RequestPermission = channel.unary_unary(
                '/ghost.NervousSystem/RequestPermission',
                request_serializer=ghost__pb2.PermissionRequest.SerializeToString,
                response_deserializer=ghost__pb2.PermissionResponse.FromString,
                _registered_method=True)
        self.StreamActions = channel.unary_stream(
                '/ghost.NervousSystem/StreamActions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ghost__pb2.ActionCommand.FromString,
                _registered_method=True)
        self.GetPendingApprovals = channel.unary_unary(
                '/ghost.NervousSystem/GetPendingApprovals',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ghost__pb2.PendingList.FromString,
                _registered_method=True)
        self.ApproveAction = channel.unary_unary(
                '/ghost.NervousSystem/ApproveAction',
                request_serializer=ghost__pb2.ApprovalDecision.SerializeToString,
                response_deserializer=ghost__pb2.Ack.FromString,
                _registered_method=True)
        self.SetSystemMode = channel.unary_unary(
                '/ghost.NervousSystem/SetSystemMode',
                request_serializer=ghost__pb2.ModeRequest.SerializeToString,
                response_deserializer=ghost__pb2.Ack.FromString,
                _registered_method=True)
        self.GetSystemState = channel.unary_unary(
                '/ghost.NervousSystem/GetSystemState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ghost__pb2.SystemState.FromString,
                _registered_method=True)


class NervousSystemServicer(object):
    """THE NERVOUS SYSTEM
    The Central Nervous System (Kernel) orchestrates all organs.
    Exposes both gRPC (High Speed) and REST HTTP (Human Dashboard).
    """

    def ReportFocus(self, request_iterator, context):
        """--- SENSORY INPUT (Body -> Kernel) ---
        Sentinel streams visual changes to Kernel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPermission(self, request, context):
        """--- COGNITION (Brain -> Kernel) ---
        Brain requests permission to act.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamActions(self, request, context):
        """--- MOTOR CONTROL (Kernel -> Body) ---
        Sentinel subscribes to a stream of approved actions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPendingApprovals(self, request, context):
        """--- HUMAN CONTROL PLANE (Gateway HTTP) ---

        UI asks: "Is there anything waiting for approval?"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAction(self, request, context):
        """User says: "Yes, do it."
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSystemMode(self, request, context):
        """User says: "Switch Mode."
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemState(self, request, context):
        """Dashboard polling for status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NervousSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportFocus': grpc.stream_unary_rpc_method_handler(
                    servicer.ReportFocus,
                    request_deserializer=ghost__pb2.FocusState.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RequestPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPermission,
                    request_deserializer=ghost__pb2.PermissionRequest.FromString,
                    response_serializer=ghost__pb2.PermissionResponse.SerializeToString,
            ),
            'StreamActions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamActions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ghost__pb2.ActionCommand.SerializeToString,
            ),
            'GetPendingApprovals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPendingApprovals,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ghost__pb2.PendingList.SerializeToString,
            ),
            'ApproveAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAction,
                    request_deserializer=ghost__pb2.ApprovalDecision.FromString,
                    response_serializer=ghost__pb2.Ack.SerializeToString,
            ),
            'SetSystemMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSystemMode,
                    request_deserializer=ghost__pb2.ModeRequest.FromString,
                    response_serializer=ghost__pb2.Ack.SerializeToString,
            ),
            'GetSystemState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ghost__pb2.SystemState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ghost.NervousSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ghost.NervousSystem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NervousSystem(object):
    """THE NERVOUS SYSTEM
    The Central Nervous System (Kernel) orchestrates all organs.
    Exposes both gRPC (High Speed) and REST HTTP (Human Dashboard).
    """

    @staticmethod
    def ReportFocus(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ghost.NervousSystem/ReportFocus',
            ghost__pb2.FocusState.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.NervousSystem/RequestPermission',
            ghost__pb2.PermissionRequest.SerializeToString,
            ghost__pb2.PermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ghost.NervousSystem/StreamActions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ghost__pb2.ActionCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPendingApprovals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.NervousSystem/GetPendingApprovals',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ghost__pb2.PendingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.NervousSystem/ApproveAction',
            ghost__pb2.ApprovalDecision.SerializeToString,
            ghost__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSystemMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.NervousSystem/SetSystemMode',
            ghost__pb2.ModeRequest.SerializeToString,
            ghost__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.NervousSystem/GetSystemState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ghost__pb2.SystemState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
